import type { CatalogItem, Rite } from "./types";

export const SEED: CatalogItem[] = [
  {
    id: "knocked-out",
    kind: "music",
    title: "Knocked Out Freestyle",
    creator: "MELITIAMARIE",
    blurb: "Prod by Melitia. The gold-mouth psalm. Play it in a room you mean to keep.",
    image: "/art/gold-mouth.jpg",
    priceUsdc: 18,
    edition: 1,
    freq: 528,
    youtubeId: "etx5MT0FD6k",
  },
  {
    id: "sore-loser",
    kind: "music",
    title: "Sore Loser Pt 1",
    creator: "MELITIAMARIE",
    blurb: "The receipt after the round. Magenta in the mouth. Keep the tape.",
    image: "/art/temple-frequency.jpg",
    priceUsdc: 14,
    edition: 1,
    freq: 432,
    youtubeId: "6AoxLX7wOiU",
  },
  {
    id: "fool-me-once",
    kind: "music",
    title: "Fool Me Once",
    creator: "MELITIAMARIE",
    blurb: "Doors cracked a finger's width. You already know the second verse.",
    image: "/art/nave-smoke.jpg",
    priceUsdc: 16,
    edition: 1,
    youtubeId: "FuVQAwNCkiI",
  },
  {
    id: "shadow-tongue",
    kind: "music",
    title: "Shadow Tongue",
    creator: "MELITIAMARIE",
    blurb: "Gold thread off the name. The verse that walks out lighter.",
    image: "/art/unbind.jpg",
    priceUsdc: 15,
    edition: 1,
    youtubeId: "dFBLLIVpuJ4",
  },
  {
    id: "she-cold",
    kind: "music",
    title: "She Cold",
    creator: "MELITIAMARIE",
    blurb: "Halo drips. Brick as chapel. 818 keeps the corner.",
    image: "/art/madonna.jpg",
    priceUsdc: 16,
    edition: 1,
    youtubeId: "H8Cmc9LKuhw",
  },
  {
    id: "nobody",
    kind: "music",
    title: "Nobody",
    creator: "MELITIAMARIE",
    blurb: "Who I am, said once. Freestyle as house name.",
    image: "/art/listener.jpg",
    priceUsdc: 12,
    edition: 1,
    freq: 396,
    youtubeId: "G3LprtMBYS0",
  },
  {
    id: "woke-up",
    kind: "music",
    title: "Woke Up",
    creator: "MELITIAMARIE",
    blurb: "Morning in the valley. The gate is already open.",
    image: "/art/open-gate.jpg",
    priceUsdc: 13,
    edition: 1,
    youtubeId: "0iAzQSucQXY",
  },
  {
    id: "wild-animal",
    kind: "music",
    title: "Wild Animal Remix",
    creator: "MELITIAMARIE",
    blurb: "ft Queeneesh. Paint as shockwave. Keep the cone at impact.",
    image: "/art/magenta-kick.jpg",
    priceUsdc: 17,
    edition: 1,
    youtubeId: "1Pd6LdvSugg",
  },
  {
    id: "serial-killah",
    kind: "music",
    title: "Serial Killah",
    creator: "MELITIAMARIE",
    blurb: "Two faces, one bargain. Gold and magenta split the vow.",
    image: "/art/deity-twin.jpg",
    priceUsdc: 19,
    edition: 1,
    youtubeId: "cok2EQVdrBU",
  },
  {
    id: "put-that-on-mama",
    kind: "music",
    title: "Put That On My Mama",
    creator: "MELITIAMARIE",
    blurb: "A vow that prefers the front door. Money walks in behind it.",
    image: "/art/return.jpg",
    priceUsdc: 15,
    edition: 1,
    youtubeId: "gxFWe-YoOC0",
  },
  {
    id: "ethereal",
    kind: "beat",
    title: "Ethereal Beat",
    creator: "MELITIAMARIE",
    blurb: "Chill type. Prod by Melitia Marie. Floor held, incense in the beam.",
    image: "/art/altar-808.jpg",
    priceUsdc: 9,
    edition: 1,
    freq: 432,
    youtubeId: "MldH_vnTJ10",
  },
  {
    id: "dubstep-fiends",
    kind: "beat",
    title: "Dubstep Mix",
    creator: "MELITIAMARIE",
    blurb: "For the beat fiends. Kick as liturgy. Gold knobs, ceremonial cords.",
    image: "/art/magenta-kick.jpg",
    priceUsdc: 11,
    edition: 1,
    freq: 396,
    youtubeId: "70jSjLfKKVU",
  },
  {
    id: "hustlegrind",
    kind: "beat",
    title: "Hustlegrindmode",
    creator: "MELITIAMARIE",
    blurb: "Dawn rite. 818 nonstop. Hold the floor until light.",
    image: "/art/altar-808.jpg",
    priceUsdc: 8,
    edition: 1,
    freq: 528,
    youtubeId: "nB6FcqY5Or4",
  },
  {
    id: "unbind-the-name",
    kind: "spell",
    title: "Unbind the Name",
    creator: "MELITIAMARIE",
    blurb: "Gold thread off the figure. The plate plays Shadow Tongue.",
    image: "/art/unbind.jpg",
    priceUsdc: 22,
    edition: 33,
    youtubeId: "dFBLLIVpuJ4",
  },
  {
    id: "open-the-gate",
    kind: "spell",
    title: "Open the Gate",
    creator: "MELITIAMARIE",
    blurb: "Magenta light. The plate plays Woke Up.",
    image: "/art/open-gate.jpg",
    priceUsdc: 16,
    edition: 21,
    youtubeId: "0iAzQSucQXY",
  },
  {
    id: "return-taken",
    kind: "spell",
    title: "Return What Was Taken",
    creator: "MELITIAMARIE",
    blurb: "Two hands, one jewel. The plate plays Fool Me Once.",
    image: "/art/return.jpg",
    priceUsdc: 28,
    edition: 13,
    youtubeId: "FuVQAwNCkiI",
  },
  {
    id: "sigil-enough",
    kind: "sigil",
    title: "I AM Enough",
    creator: "THE REDUCER",
    blurb: "Intent reduced. Vowels burned. The remaining letters lock to Nobody.",
    image: "/art/grimoire-plate.jpg",
    priceUsdc: 13,
    edition: 1,
    intent: "I AM ENOUGH",
    reduced: "MNGH",
    youtubeId: "G3LprtMBYS0",
  },
  {
    id: "sigil-wealth",
    kind: "sigil",
    title: "Wealth Walks In",
    creator: "THE REDUCER",
    blurb: "A chevron lock for money. The plate plays Put That On My Mama.",
    image: "/art/grimoire-plate-alt.jpg",
    priceUsdc: 19,
    edition: 1,
    intent: "WEALTH WALKS IN",
    reduced: "WLTHKSN",
    youtubeId: "gxFWe-YoOC0",
  },
  {
    id: "gold-masked-twin",
    kind: "deity",
    title: "The Gold-Masked Twin",
    creator: "NAVE WORKS",
    blurb: "Two faces, one bargain. The nave plays Serial Killah.",
    image: "/art/deity-twin.jpg",
    priceUsdc: 44,
    edition: 7,
    youtubeId: "cok2EQVdrBU",
  },
  {
    id: "magenta-madonna",
    kind: "deity",
    title: "Madonna of the Block",
    creator: "NAVE WORKS",
    blurb: "Halo drips. She keeps the corner. The nave plays She Cold.",
    image: "/art/madonna.jpg",
    priceUsdc: 36,
    edition: 9,
    youtubeId: "H8Cmc9LKuhw",
  },
  {
    id: "the-listener",
    kind: "deity",
    title: "The Listener",
    creator: "NAVE WORKS",
    blurb: "Every frequency finds an ear. The nave plays Night Visions.",
    image: "/art/listener.jpg",
    priceUsdc: 40,
    edition: 5,
    youtubeId: "fgHrvPrnLao",
  },
  {
    id: "quote-frequency",
    kind: "quote",
    title: "Frequency",
    creator: "I AM",
    blurb: "The house text. Frame it or forget it. Plays Knocked Out.",
    image: "/art/lectern.jpg",
    priceUsdc: 5,
    edition: 108,
    quote: "I AM is not a name. It is a frequency.",
    youtubeId: "etx5MT0FD6k",
  },
  {
    id: "quote-altar",
    kind: "quote",
    title: "The Receipt",
    creator: "I AM",
    blurb: "Pay, keep paper, leave. Plays Sore Loser.",
    image: "/art/nave-smoke.jpg",
    priceUsdc: 4,
    edition: 88,
    quote: "Pay the altar. Keep the receipt.",
    youtubeId: "6AoxLX7wOiU",
  },
  {
    id: "quote-tag",
    kind: "quote",
    title: "Tag as Prayer",
    creator: "I AM",
    blurb: "Meaning is the only pigment that holds. Plays Ethereal.",
    image: "/art/open-gate.jpg",
    priceUsdc: 6,
    edition: 64,
    quote: "Every tag is a prayer if you mean it.",
    youtubeId: "MldH_vnTJ10",
  },
];

export const FEATURED_IDS = [
  "knocked-out",
  "she-cold",
  "woke-up",
  "nobody",
] as const;

export const RITES: Rite[] = [
  {
    id: "rite-knocked",
    title: "Knocked Out Freestyle",
    artist: "MELITIAMARIE",
    slot: "Live in the nave",
    freq: 528,
    priceUsdc: 18,
    image: "/art/gold-mouth.jpg",
    blurb: "The gold-mouth psalm for the nave. The ticket holds the tape open.",
    youtubeId: "etx5MT0FD6k",
  },
  {
    id: "rite-ethereal",
    title: "Ethereal Beat",
    artist: "MELITIAMARIE",
    slot: "Tonight · second bell",
    freq: 432,
    priceUsdc: 12,
    image: "/art/altar-808.jpg",
    blurb: "Incense, 432Hz, gold dust in the beam.",
    youtubeId: "MldH_vnTJ10",
  },
  {
    id: "rite-hustle",
    title: "Hustlegrindmode",
    artist: "MELITIAMARIE",
    slot: "Dawn rite",
    freq: 396,
    priceUsdc: 8,
    image: "/art/altar-808.jpg",
    blurb: "Kick as liturgy. Hold the floor until light.",
    youtubeId: "nB6FcqY5Or4",
  },
];

export const HOUSE_ARTIST = "MELITIAMARIE";

export const MINT_FEE_USDC = 4;

export const SHOUT_TIERS = [3, 8, 18] as const;

export function mergeCatalog(minted: CatalogItem[]): CatalogItem[] {
  const mintedIds = new Set(minted.map((m) => m.id));
  return [...minted, ...SEED.filter((s) => !mintedIds.has(s.id))];
}

export function isPlayable(item: {
  audioSrc?: string;
  youtubeId?: string;
  tapeId?: string;
  soundcloudUrl?: string;
}) {
  return Boolean(
    item.audioSrc || item.youtubeId || item.tapeId || item.soundcloudUrl,
  );
}
