import type { CatalogItem } from "./types";

const ART = [
  "/art/gold-mouth.jpg",
  "/art/temple-frequency.jpg",
  "/art/nave-smoke.jpg",
  "/art/unbind.jpg",
  "/art/madonna.jpg",
  "/art/listener.jpg",
  "/art/open-gate.jpg",
  "/art/magenta-kick.jpg",
  "/art/deity-twin.jpg",
  "/art/return.jpg",
  "/art/altar-808.jpg",
  "/art/lectern.jpg",
  "/art/hero.jpg",
  "/art/sigil-circle.jpg",
  "/art/sigil-chevron.jpg",
  "/art/emblem.jpg",
] as const;

function cover(i: number) {
  return ART[i % ART.length];
}

/** Extra Melitiamarie YouTube tapes not already in the seed altar. */
export const EXTRA_TAPES: CatalogItem[] = [
  {
    id: "light-language",
    kind: "music",
    title: "Eyah Oh Si Na",
    creator: "MELITIAMARIE",
    blurb: "Light language. Healing drum and bass. The nave speaks in tone.",
    image: cover(0),
    priceUsdc: 14,
    edition: 1,
    freq: 528,
    youtubeId: "2GA4hrY06sY",
  },
  {
    id: "dont-wanna-wait",
    kind: "beat",
    title: "I Don't Wanna Wait",
    creator: "MELITIAMARIE",
    blurb: "EDM Melitia mix. Eight minutes of the floor held.",
    image: cover(1),
    priceUsdc: 11,
    edition: 1,
    youtubeId: "lNC21Wd3ODw",
  },
  {
    id: "night-visions",
    kind: "music",
    title: "Night Visions",
    creator: "MELITIAMARIE",
    blurb: "ft Younginbeats. Every frequency finds an ear.",
    image: cover(5),
    priceUsdc: 15,
    edition: 1,
    youtubeId: "fgHrvPrnLao",
  },
  {
    id: "as-above-pt2",
    kind: "music",
    title: "As Above Pt 2",
    creator: "MELITIAMARIE",
    blurb: "The second plate of the vow. Gold above, magenta below.",
    image: cover(8),
    priceUsdc: 14,
    edition: 1,
    youtubeId: "hu3BuKhOJi0",
  },
  {
    id: "sinner",
    kind: "music",
    title: "Sinner",
    creator: "MELITIAMARIE",
    blurb: "Confession as a 1/1. Keep the receipt.",
    image: cover(3),
    priceUsdc: 13,
    edition: 1,
    youtubeId: "c-4-JvEI9EI",
  },
  {
    id: "came-up",
    kind: "music",
    title: "Came Up",
    creator: "MELITIAMARIE",
    blurb: "The come-up pressed to foil. 818 in the mouth.",
    image: cover(6),
    priceUsdc: 16,
    edition: 1,
    youtubeId: "bH8GjfHSBq0",
  },
  {
    id: "treat-colors",
    kind: "music",
    title: "Treat Colors",
    creator: "MELITIAMARIE",
    blurb: "Pigment as prayer. Magenta running the scale.",
    image: cover(7),
    priceUsdc: 12,
    edition: 1,
    youtubeId: "L5aBsx3duUA",
  },
  {
    id: "scarfacebarz",
    kind: "music",
    title: "Scarfacebarz",
    creator: "MELITIAMARIE",
    blurb: "Bars cut on gold. The house keeps this one mean.",
    image: cover(9),
    priceUsdc: 15,
    edition: 1,
    youtubeId: "nWmvQb3_pc8",
  },
  {
    id: "see-thru",
    kind: "music",
    title: "See Thru",
    creator: "MELITIAMARIE",
    blurb: "ft Doomstarr. Glass in the nave. You already know.",
    image: cover(4),
    priceUsdc: 14,
    edition: 1,
    youtubeId: "4MBRUUyEQc8",
  },
  {
    id: "bee-free",
    kind: "music",
    title: "Bee Free",
    creator: "MELITIAMARIE",
    blurb: "with Eternal & Nakeva Bryant. Life after the trial.",
    image: cover(2),
    priceUsdc: 16,
    edition: 1,
    youtubeId: "sA2zf_fI_mI",
  },
  {
    id: "hustla-818",
    kind: "music",
    title: "818 Hustla",
    creator: "MELITIAMARIE",
    blurb: "Valley plate. SFV in the stamp. Nonstop.",
    image: cover(10),
    priceUsdc: 13,
    edition: 1,
    freq: 396,
    youtubeId: "L6KsupPzN-s",
  },
  {
    id: "guitar-528",
    kind: "beat",
    title: "528Hz Guitar Heart",
    creator: "MELITIAMARIE",
    blurb: "Gentle lofi binaural. The strings of the nave.",
    image: cover(12),
    priceUsdc: 9,
    edition: 1,
    freq: 528,
    youtubeId: "jSUyy5GCKOQ",
  },
  {
    id: "lockdown",
    kind: "music",
    title: "Lockdown",
    creator: "MELITIAMARIE",
    blurb: "ft Kasper. The gate held. Play it closed-room.",
    image: cover(11),
    priceUsdc: 14,
    edition: 1,
    youtubeId: "mHDLhbrVqVM",
  },
  {
    id: "hollow-points",
    kind: "music",
    title: "Hollow Points",
    creator: "MELITIAMARIE",
    blurb: "Sharp plate. Collect if you mean the round.",
    image: cover(13),
    priceUsdc: 15,
    edition: 1,
    youtubeId: "IhQkfwTjRLg",
  },
  {
    id: "free-my-dawgz",
    kind: "music",
    title: "Free My Dawgz",
    creator: "MELITIAMARIE",
    blurb: "Behind the walls remix. The house does not forget.",
    image: cover(3),
    priceUsdc: 14,
    edition: 1,
    youtubeId: "dQ5ecEoLfyA",
  },
  {
    id: "wtf-i-look-like",
    kind: "music",
    title: "Wtf I Look Like",
    creator: "MELITIAMARIE",
    blurb: "Freestyle as name. The gold mouth, open.",
    image: cover(0),
    priceUsdc: 12,
    edition: 1,
    youtubeId: "OnEvXPPrO_M",
  },
  {
    id: "collective-thoughts",
    kind: "music",
    title: "Collective Thoughts",
    creator: "MELITIAMARIE",
    blurb: "ft 2tiller. The room thinks together.",
    image: cover(5),
    priceUsdc: 13,
    edition: 1,
    youtubeId: "pIDscIiEVXI",
  },
  {
    id: "mentally-unstable",
    kind: "music",
    title: "Mentally Unstable",
    creator: "MELITIAMARIE",
    blurb: "Freestyle. Honest plate. No polish on the vow.",
    image: cover(8),
    priceUsdc: 12,
    edition: 1,
    youtubeId: "3V3N1TuSZ3s",
  },
  {
    id: "life-i-lead",
    kind: "music",
    title: "The Life I Lead",
    creator: "MELITIAMARIE",
    blurb: "The path as a 1/1. Keep it in the vault.",
    image: cover(6),
    priceUsdc: 14,
    edition: 1,
    youtubeId: "UTnfIYSg45g",
  },
  {
    id: "jeepers-creepers",
    kind: "music",
    title: "Jeepers Creepers",
    creator: "MELITIAMARIE",
    blurb: "Night plate. The nave looks back.",
    image: cover(14),
    priceUsdc: 13,
    edition: 1,
    youtubeId: "l2DIVynrb9E",
  },
  {
    id: "type-shit-remix",
    kind: "beat",
    title: "Type Shit Remix",
    creator: "MELITIAMARIE",
    blurb: "Melitiamarie type. The booth stamp.",
    image: cover(7),
    priceUsdc: 10,
    edition: 1,
    youtubeId: "NoMJX8KTyfk",
  },
  {
    id: "speak-on-this",
    kind: "music",
    title: "Speak On This",
    creator: "MELITIAMARIE",
    blurb: "Freestyle. Say it once. Collect the tape.",
    image: cover(15),
    priceUsdc: 12,
    edition: 1,
    youtubeId: "jMS7RJKEF9w",
  },
];
