/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AltarRouteImport } from './routes/altar'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as GrimoireRouteImport } from './routes/grimoire'
import { Route as HouseRouteImport } from './routes/house'
import { Route as InstallRouteImport } from './routes/install'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MintRouteImport } from './routes/mint'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as StageRouteImport } from './routes/stage'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VaultRouteImport } from './routes/vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AltarRoute = AltarRouteImport.update({
  id: '/altar',
  path: '/altar',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const GrimoireRoute = GrimoireRouteImport.update({
  id: '/grimoire',
  path: '/grimoire',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MintRoute = MintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StageRoute = StageRouteImport.update({
  id: '/stage',
  path: '/stage',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/altar': typeof AltarRoute
  '/feed': typeof FeedRoute
  '/grimoire': typeof GrimoireRoute
  '/house': typeof HouseRoute
  '/install': typeof InstallRoute
  '/market': typeof MarketRoute
  '/mint': typeof MintRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/stage': typeof StageRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/altar': typeof AltarRoute
  '/feed': typeof FeedRoute
  '/grimoire': typeof GrimoireRoute
  '/house': typeof HouseRoute
  '/install': typeof InstallRoute
  '/market': typeof MarketRoute
  '/mint': typeof MintRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/stage': typeof StageRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/altar': typeof AltarRoute
  '/feed': typeof FeedRoute
  '/grimoire': typeof GrimoireRoute
  '/house': typeof HouseRoute
  '/install': typeof InstallRoute
  '/market': typeof MarketRoute
  '/mint': typeof MintRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/stage': typeof StageRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/altar'
    | '/feed'
    | '/grimoire'
    | '/house'
    | '/install'
    | '/market'
    | '/mint'
    | '/privacy'
    | '/scan'
    | '/stage'
    | '/support'
    | '/terms'
    | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/altar'
    | '/feed'
    | '/grimoire'
    | '/house'
    | '/install'
    | '/market'
    | '/mint'
    | '/privacy'
    | '/scan'
    | '/stage'
    | '/support'
    | '/terms'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/altar'
    | '/feed'
    | '/grimoire'
    | '/house'
    | '/install'
    | '/market'
    | '/mint'
    | '/privacy'
    | '/scan'
    | '/stage'
    | '/support'
    | '/terms'
    | '/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AltarRoute: typeof AltarRoute
  FeedRoute: typeof FeedRoute
  GrimoireRoute: typeof GrimoireRoute
  HouseRoute: typeof HouseRoute
  InstallRoute: typeof InstallRoute
  MarketRoute: typeof MarketRoute
  MintRoute: typeof MintRoute
  PrivacyRoute: typeof PrivacyRoute
  ScanRoute: typeof ScanRoute
  StageRoute: typeof StageRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/altar': {
      id: '/altar'
      path: '/altar'
      fullPath: '/altar'
      preLoaderRoute: typeof AltarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grimoire': {
      id: '/grimoire'
      path: '/grimoire'
      fullPath: '/grimoire'
      preLoaderRoute: typeof GrimoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mint': {
      id: '/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof MintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage': {
      id: '/stage'
      path: '/stage'
      fullPath: '/stage'
      preLoaderRoute: typeof StageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AltarRoute: AltarRoute,
  FeedRoute: FeedRoute,
  GrimoireRoute: GrimoireRoute,
  HouseRoute: HouseRoute,
  InstallRoute: InstallRoute,
  MarketRoute: MarketRoute,
  MintRoute: MintRoute,
  PrivacyRoute: PrivacyRoute,
  ScanRoute: ScanRoute,
  StageRoute: StageRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
